app:
  name: "Ouch Client"
  desc: "Ouch Client IDX Exchange Order Gateway"
  env: "development" #development, mock, staging, production
  version: "1.0.0"
  storage_path: "./storage_mme"

logger:
  default:
    level: info
    output: stdout
    format: text
    dir: ./storage_mme/logs
  logs:
    service:
      enabled: true
      filename: sinx_gate_service #sinx_gate_service_2026-05-15.log
      output: [stdout, file]
      level: debug
    ouch:
      enabled: true
      filename: ouch_message #ouch_message_2026-05-15.log
      output: [stdout]
      level: debug
    itch:
      enabled: true
      filename: itch_message #ouch_message_2026-05-15.log
      output: [stdout]
      level: debug

tcp:
  clients:
    - name: ouch client 1
      run: true
      host: 127.0.0.1
      port: 8600
      username: YJJOE1
      password: P@ssw0rd!1
      requested_sequence: ""
      heartbeat_interval: 1s
      dial_timeout: 10s
      reconnect_delay: 1s
      keep_alive: 30s
    - name: ouch client 2
      run: true
      host: 127.0.0.1
      port: 8600
      username: YJJOE2
      password: P@ssw0rd!1
      requested_sequence: ""
      heartbeat_interval: 1s
      dial_timeout: 10s
      reconnect_delay: 1s
      keep_alive: 30s
